### ISSUE TITLE
Modules will not load.

### ISSUE THREAD

**Issue by zfouts** [ThePlatzhalter/InspIRCD#1]
Receiving the following error when trying to load the gnutls (or openssl) modules. Actually, any modules.

Do you have any suggestion? Thanks!
```
Inspire Internet Relay Chat Server, compiled on Oct 29 2016 at 19:37:43
(C) InspIRCd Development Team.

Developers:
    Brain, FrostyCoolSlug, w00t, Om, Special, peavey
    aquanight, psychon, dz, danieldg, jackmcbarn
    Attila

Others:            See /INFO Output


Loading core commands.....................................................
[*] Loading module:    gnutls

[*] Module file could not be found: gnutls
```

**Comment by ThePlatzhalter** [comment]
I'm sorry I did not reply immediately. I was offline for a bit. I'm going to have a look at it now though! :)

**Comment by ThePlatzhalter** [comment]
Could you post your configuration please? @zfouts

**Comment by zfouts** [comment]
@ThePlatzhalter  oh my bad, I actually scrapped the project. Sorry. I was using the default inspircd config though.

**Comment by ThePlatzhalter** [comment]
@zfouts oh okay. i'm sorry to hear that.
